CREATE DATABASE IF NOT EXISTS ideophone_arena
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE ideophone_arena;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS player_answers;
DROP TABLE IF EXISTS game_sessions;
DROP TABLE IF EXISTS arena_rounds;
DROP TABLE IF EXISTS ideophones;
DROP TABLE IF EXISTS app_users;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE app_users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL
        UNIQUE,
    email VARCHAR(255) NOT NULL
        UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'ROLE_USER',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE ideophones (
    id BIGINT NOT NULL AUTO_INCREMENT,
    kana VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    romaji VARCHAR(100) NOT NULL,
    gloss VARCHAR(255) NOT NULL,
    canonical_script VARCHAR(20) NOT NULL,
    stimulus_file VARCHAR(100) NOT NULL
        UNIQUE,
    modality VARCHAR(50),

    PRIMARY KEY (id),
    UNIQUE (kana, canonical_script)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE arena_rounds (
    id BIGINT NOT NULL AUTO_INCREMENT,
    prompt VARCHAR(255) NOT NULL,
    left_ideophone_id BIGINT NOT NULL,
    right_ideophone_id BIGINT NOT NULL,
    correct_ideophone_id BIGINT NOT NULL,
    condition_name VARCHAR(50) NOT NULL DEFAULT 'TEXT_ONLY',
    difficulty_level INT NOT NULL DEFAULT 1,

    PRIMARY KEY (id),

    CONSTRAINT fk_round_left_ideophone
        FOREIGN KEY (left_ideophone_id)
            REFERENCES ideophones (id),

    CONSTRAINT fk_round_right_ideophone
        FOREIGN KEY (right_ideophone_id)
            REFERENCES ideophones (id),

    CONSTRAINT fk_round_correct_ideophone
        FOREIGN KEY (correct_ideophone_id)
            REFERENCES ideophones (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE game_sessions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    session_uuid CHAR(36) NOT NULL
        UNIQUE,
    user_id BIGINT NOT NULL,
    difficulty_level INT NOT NULL DEFAULT 1,
    condition_name VARCHAR(50) NOT NULL DEFAULT 'TEXT_ONLY',
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL,

    PRIMARY KEY (id),

    CONSTRAINT fk_game_sessions_user
        FOREIGN KEY (user_id)
            REFERENCES app_users (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE player_answers (
    id BIGINT NOT NULL AUTO_INCREMENT,
    session_id BIGINT NOT NULL,
    round_id BIGINT NOT NULL,
    selected_ideophone_id BIGINT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    response_time_ms INT,
    answered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE (session_id, round_id),

    CONSTRAINT fk_answers_session
        FOREIGN KEY (session_id)
            REFERENCES game_sessions (id),

    CONSTRAINT fk_answers_round
        FOREIGN KEY (round_id)
            REFERENCES arena_rounds (id),

    CONSTRAINT fk_answers_selected_ideophone
        FOREIGN KEY (selected_ideophone_id)
            REFERENCES ideophones (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Seed data generated from src/main/resources/condition-*-choosing-sokuon.csv.
INSERT INTO ideophones (id, kana, romaji, gloss, canonical_script, stimulus_file, modality)
VALUES
(1, 'ごそごそ', 'gosogoso', 'with a rustling sound', 'HU', 'a0hu-gosogoso.mp4', 'AUDITORY'),
(2, 'かたかた', 'katakata', 'clattering, rattling', 'KD', 'a0kd-katakata.mp4', 'AUDITORY'),
(3, 'しとしと', 'sitosito', 'drizzling', 'HU', 'a1hu-sitosito.mp4', 'AUDITORY'),
(4, 'ばちゃばちゃ', 'batyabatya', 'splashing', 'KD', 'a1kd-batyabatya.mp4', 'AUDITORY'),
(5, 'じゃあじゃあ', 'zyaazyaa', 'noisily gushing', 'HU', 'a2hu-zyaazyaa.mp4', 'AUDITORY'),
(6, 'ぽたぽた', 'potapota', 'dripping, trickling', 'KD', 'a2kd-potapota.mp4', 'AUDITORY'),
(7, 'じりじり', 'ziriziri', 'sizzling, oozing', 'HU', 'a3hu-ziriziri.mp4', 'AUDITORY'),
(8, 'しゃきしゃき', 'syakisyaki', 'crisp, crunchy', 'KD', 'a3kd-syakisyaki.mp4', 'AUDITORY'),
(9, 'ずるずる', 'zuruzuru', 'with a slurp', 'HU', 'a4hu-zuruzuru.mp4', 'AUDITORY'),
(10, 'ぽりぽり', 'poripori', 'munching, crunching', 'KD', 'a4kd-poripori.mp4', 'AUDITORY'),
(11, 'そろりそろり', 'sororisorori', 'slowly and quietly', 'HU', 'a5hu-sororisorori.mp4', 'AUDITORY'),
(12, 'どたばた', 'dotabata', 'noisily, with heavy feet', 'KD', 'a5kd-dotabata.mp4', 'AUDITORY'),
(13, 'どさり', 'dosari', 'with a thud', 'HU', 'a6hu-dosari.mp4', 'AUDITORY'),
(14, 'かちっ', 'katiQ', 'click, snap', 'KD', 'a6kd-katiQ.mp4', 'AUDITORY'),
(15, 'どしどし', 'dosidosi', 'tramping, stomping', 'HU', 'a7hu-dosidosi.mp4', 'AUDITORY'),
(16, 'ぎしぎし', 'gisigisi', 'with a creak, squeak', 'KD', 'a7kd-gisigisi.mp4', 'AUDITORY'),
(17, 'ぼそり', 'bosori', 'in a whisper, in a murmur', 'HU', 'a8hu-bosori.mp4', 'AUDITORY'),
(18, 'きゃあきゃあ', 'kyaakyaa', 'shrieking, squealing', 'KD', 'a8kd-kyaakyaa.mp4', 'AUDITORY'),
(19, 'もごもご', 'mogomogo', 'mumbling, chewing', 'HU', 'a9hu-mogomogo.mp4', 'AUDITORY'),
(20, 'さくっ', 'sakuQ', 'with a crunch', 'KD', 'a9kd-sakuQ.mp4', 'AUDITORY'),
(21, 'くっきり', 'kukkiri', 'clearly, distinctly, sharply', 'HU', 'v0hu-kukkiri.mp4', 'VISUAL'),
(22, 'ちらちら', 'tiratira', 'flickering, fluttering', 'KD', 'v0kd-tiratira.mp4', 'VISUAL'),
(23, 'くりくり', 'kurikuri', 'big and round', 'HU', 'v1hu-kurikuri.mp4', 'VISUAL'),
(24, 'ぎざぎざ', 'gizagiza', 'jagged, serrated', 'KD', 'v1kd-gizagiza.mp4', 'VISUAL'),
(25, 'どんより', 'doNyori', 'dark, gloomy', 'HU', 'v2hu-doNyori.mp4', 'VISUAL'),
(26, 'きらきら', 'kirakira', 'glittering, sparkling', 'KD', 'v2kd-kirakira.mp4', 'VISUAL'),
(27, 'ぴたり', 'pitari', 'tightly connected, no space in between', 'HU', 'v3hu-pitari.mp4', 'VISUAL'),
(28, 'ひらひら', 'hirahira', 'fluttering, dangling', 'KD', 'v3kd-hirahira.mp4', 'VISUAL'),
(29, 'びっしり', 'bissiri', 'closely lined up, densely', 'HU', 'v4hu-bissiri.mp4', 'VISUAL'),
(30, 'ばらばら', 'barabara', 'scattered, in pieces', 'KD', 'v4kd-barabara.mp4', 'VISUAL'),
(31, 'ぶすり', 'busuri', 'poutingly, displeasure', 'HU', 'v5hu-busuri.mp4', 'VISUAL'),
(32, 'にこにこ', 'nikoniko', 'smilingly, with a grin', 'KD', 'v5kd-nikoniko.mp4', 'VISUAL'),
(33, 'ふんわり', 'huNwari', 'gently, airily, fluffy', 'HU', 'v6hu-huNwari.mp4', 'VISUAL'),
(34, 'ごつごつ', 'gotugotu', 'rugged, scragged, angular', 'KD', 'v6kd-gotugotu.mp4', 'VISUAL'),
(35, 'ぼんやり', 'boNyari', 'dim, faint, indistinct', 'HU', 'v7hu-boNyari.mp4', 'VISUAL'),
(36, 'きりっ', 'kiriQ', 'crisp appearance, stiffly', 'KD', 'v7kd-kiriQ.mp4', 'VISUAL'),
(37, 'まるまる', 'marumaru', 'plump, rotund, chubby', 'HU', 'v8hu-marumaru.mp4', 'VISUAL'),
(38, 'がりがり', 'garigari', 'very skinny, emaciated', 'KD', 'v8kd-garigari.mp4', 'VISUAL'),
(39, 'むくむく', 'mukumuku', 'billowing, plump', 'HU', 'v9hu-mukumuku.mp4', 'VISUAL'),
(40, 'ぼさぼさ', 'bosabosa', 'ruffled, disheveled', 'KD', 'v9kd-bosabosa.mp4', 'VISUAL'),
(41, 'うんざり', 'uNzari', 'boredom, tedious, fed up with', 'HU', 'i0hu-uNzari.mp4', 'INTEROCEPTIVE'),
(42, 'わくわく', 'wakuwaku', 'excitement, nervous', 'KD', 'i0kd-wakuwaku.mp4', 'INTEROCEPTIVE'),
(43, 'げんなり', 'geNnari', 'weary, fed up, dejected', 'HU', 'i1hu-geNnari.mp4', 'INTEROCEPTIVE'),
(44, 'がつがつ', 'gatugatu', 'ravenously, greedily', 'KD', 'i1kd-gatugatu.mp4', 'INTEROCEPTIVE'),
(45, 'しょぼん', 'syoboN', 'downhearted, dejected', 'HU', 'i2hu-syoboN.mp4', 'INTEROCEPTIVE'),
(46, 'るんるん', 'ruNruN', 'happy, elated, euphoric', 'KD', 'i2kd-ruNruN.mp4', 'INTEROCEPTIVE'),
(47, 'すっきり', 'sukkiri', 'refreshingly, with a feeling fo relief', 'HU', 'i3hu-sukkiri.mp4', 'INTEROCEPTIVE'),
(48, 'いらいら', 'iraira', 'to get irritated, annoyed', 'KD', 'i3kd-iraira.mp4', 'INTEROCEPTIVE'),
(49, 'ちゃんと', 'tyaNto', 'attentive, proper attitude', 'HU', 'i4hu-tyaNto.mp4', 'INTEROCEPTIVE'),
(50, 'どぎまぎ', 'dogimagi', 'flurried, nervous', 'KD', 'i4kd-dogimagi.mp4', 'INTEROCEPTIVE'),
(51, 'のびのび', 'nobinobi', 'comfortable, peaceful', 'HU', 'i5hu-nobinobi.mp4', 'INTEROCEPTIVE'),
(52, 'はらはら', 'harahara', 'anxious, nervous', 'KD', 'i5kd-harahara.mp4', 'INTEROCEPTIVE'),
(53, 'のんびり', 'noNbiri', 'at leisure, in a relaxed manner', 'HU', 'i6hu-noNbiri.mp4', 'INTEROCEPTIVE'),
(54, 'ぎりぎり', 'girigiri', 'just barely, at the last moment', 'KD', 'i6kd-girigiri.mp4', 'INTEROCEPTIVE'),
(55, 'ほっこり', 'hokkori', 'feeling warm and fluffy, soft', 'HU', 'i7hu-hokkori.mp4', 'INTEROCEPTIVE'),
(56, 'ぞくぞく', 'zokuzoku', 'shivering, feeling chilly', 'KD', 'i7kd-zokuzoku.mp4', 'INTEROCEPTIVE'),
(57, 'ほっ', 'hoQ', 'with a feeling of relief', 'HU', 'i8hu-hoQ.mp4', 'INTEROCEPTIVE'),
(58, 'どきり', 'dokiri', 'being startled, getting a shock', 'KD', 'i8kd-dokiri.mp4', 'INTEROCEPTIVE'),
(59, 'ゆったり', 'yuttari', 'comfortable, calm, relaxed', 'HU', 'i9hu-yuttari.mp4', 'INTEROCEPTIVE'),
(60, 'どきどき', 'dokidoki', 'with a rapid heartbeat', 'KD', 'i9kd-dokidoki.mp4', 'INTEROCEPTIVE'),
(61, 'ごそごそ', 'gosogoso', 'with a rustling sound', 'HH', 'a0hh-gosogoso.mp4', 'AUDITORY'),
(62, 'かたかた', 'katakata', 'clattering, rattling', 'KK', 'a0kk-katakata.mp4', 'AUDITORY'),
(63, 'しとしと', 'sitosito', 'drizzling', 'HH', 'a1hh-sitosito.mp4', 'AUDITORY'),
(64, 'ばちゃばちゃ', 'batyabatya', 'splashing', 'KK', 'a1kk-batyabatya.mp4', 'AUDITORY'),
(65, 'じゃあじゃあ', 'zyaazyaa', 'noisily gushing', 'HH', 'a2hh-zyaazyaa.mp4', 'AUDITORY'),
(66, 'ぽたぽた', 'potapota', 'dripping, trickling', 'KK', 'a2kk-potapota.mp4', 'AUDITORY'),
(67, 'じりじり', 'ziriziri', 'sizzling, oozing', 'HH', 'a3hh-ziriziri.mp4', 'AUDITORY'),
(68, 'しゃきしゃき', 'syakisyaki', 'crisp, crunchy', 'KK', 'a3kk-syakisyaki.mp4', 'AUDITORY'),
(69, 'ずるずる', 'zuruzuru', 'with a slurp', 'HH', 'a4hh-zuruzuru.mp4', 'AUDITORY'),
(70, 'ぽりぽり', 'poripori', 'munching, crunching', 'KK', 'a4kk-poripori.mp4', 'AUDITORY'),
(71, 'そろりそろり', 'sororisorori', 'slowly and quietly', 'HH', 'a5hh-sororisorori.mp4', 'AUDITORY'),
(72, 'どたばた', 'dotabata', 'noisily, with heavy feet', 'KK', 'a5kk-dotabata.mp4', 'AUDITORY'),
(73, 'どさり', 'dosari', 'with a thud', 'HH', 'a6hh-dosari.mp4', 'AUDITORY'),
(74, 'かちっ', 'katiQ', 'click, snap', 'KK', 'a6kk-katiQ.mp4', 'AUDITORY'),
(75, 'どしどし', 'dosidosi', 'tramping, stomping', 'HH', 'a7hh-dosidosi.mp4', 'AUDITORY'),
(76, 'ぎしぎし', 'gisigisi', 'with a creak, squeak', 'KK', 'a7kk-gisigisi.mp4', 'AUDITORY'),
(77, 'ぼそり', 'bosori', 'in a whisper, in a murmur', 'HH', 'a8hh-bosori.mp4', 'AUDITORY'),
(78, 'きゃあきゃあ', 'kyaakyaa', 'shrieking, squealing', 'KK', 'a8kk-kyaakyaa.mp4', 'AUDITORY'),
(79, 'もごもご', 'mogomogo', 'mumbling, chewing', 'HH', 'a9hh-mogomogo.mp4', 'AUDITORY'),
(80, 'さくっ', 'sakuQ', 'with a crunch', 'KK', 'a9kk-sakuQ.mp4', 'AUDITORY'),
(81, 'くっきり', 'kukkiri', 'clearly, distinctly, sharply', 'HH', 'v0hh-kukkiri.mp4', 'VISUAL'),
(82, 'ちらちら', 'tiratira', 'flickering, fluttering', 'KK', 'v0kk-tiratira.mp4', 'VISUAL'),
(83, 'くりくり', 'kurikuri', 'big and round', 'HH', 'v1hh-kurikuri.mp4', 'VISUAL'),
(84, 'ぎざぎざ', 'gizagiza', 'jagged, serrated', 'KK', 'v1kk-gizagiza.mp4', 'VISUAL'),
(85, 'どんより', 'doNyori', 'dark, gloomy', 'HH', 'v2hh-doNyori.mp4', 'VISUAL'),
(86, 'きらきら', 'kirakira', 'glittering, sparkling', 'KK', 'v2kk-kirakira.mp4', 'VISUAL'),
(87, 'ぴたり', 'pitari', 'tightly connected, no space in between', 'HH', 'v3hh-pitari.mp4', 'VISUAL'),
(88, 'ひらひら', 'hirahira', 'fluttering, dangling', 'KK', 'v3kk-hirahira.mp4', 'VISUAL'),
(89, 'びっしり', 'bissiri', 'closely lined up, densely', 'HH', 'v4hh-bissiri.mp4', 'VISUAL'),
(90, 'ばらばら', 'barabara', 'scattered, in pieces', 'KK', 'v4kk-barabara.mp4', 'VISUAL'),
(91, 'ぶすり', 'busuri', 'poutingly, displeasure', 'HH', 'v5hh-busuri.mp4', 'VISUAL'),
(92, 'にこにこ', 'nikoniko', 'smilingly, with a grin', 'KK', 'v5kk-nikoniko.mp4', 'VISUAL'),
(93, 'ふんわり', 'huNwari', 'gently, airily, fluffy', 'HH', 'v6hh-huNwari.mp4', 'VISUAL'),
(94, 'ごつごつ', 'gotugotu', 'rugged, scragged, angular', 'KK', 'v6kk-gotugotu.mp4', 'VISUAL'),
(95, 'ぼんやり', 'boNyari', 'dim, faint, indistinct', 'HH', 'v7hh-boNyari.mp4', 'VISUAL'),
(96, 'きりっ', 'kiriQ', 'crisp appearance, stiffly', 'KK', 'v7kk-kiriQ.mp4', 'VISUAL'),
(97, 'まるまる', 'marumaru', 'plump, rotund, chubby', 'HH', 'v8hh-marumaru.mp4', 'VISUAL'),
(98, 'がりがり', 'garigari', 'very skinny, emaciated', 'KK', 'v8kk-garigari.mp4', 'VISUAL'),
(99, 'むくむく', 'mukumuku', 'billowing, plump', 'HH', 'v9hh-mukumuku.mp4', 'VISUAL'),
(100, 'ぼさぼさ', 'bosabosa', 'ruffled, disheveled', 'KK', 'v9kk-bosabosa.mp4', 'VISUAL'),
(101, 'うんざり', 'uNzari', 'boredom, tedious, fed up with', 'HH', 'i0hh-uNzari.mp4', 'INTEROCEPTIVE'),
(102, 'わくわく', 'wakuwaku', 'excitement, nervous', 'KK', 'i0kk-wakuwaku.mp4', 'INTEROCEPTIVE'),
(103, 'げんなり', 'geNnari', 'weary, fed up, dejected', 'HH', 'i1hh-geNnari.mp4', 'INTEROCEPTIVE'),
(104, 'がつがつ', 'gatugatu', 'ravenously, greedily', 'KK', 'i1kk-gatugatu.mp4', 'INTEROCEPTIVE'),
(105, 'しょぼん', 'syoboN', 'downhearted, dejected', 'HH', 'i2hh-syoboN.mp4', 'INTEROCEPTIVE'),
(106, 'るんるん', 'ruNruN', 'happy, elated, euphoric', 'KK', 'i2kk-ruNruN.mp4', 'INTEROCEPTIVE'),
(107, 'すっきり', 'sukkiri', 'refreshingly, with a feeling fo relief', 'HH', 'i3hh-sukkiri.mp4', 'INTEROCEPTIVE'),
(108, 'いらいら', 'iraira', 'to get irritated, annoyed', 'KK', 'i3kk-iraira.mp4', 'INTEROCEPTIVE'),
(109, 'ちゃんと', 'tyaNto', 'attentive, proper attitude', 'HH', 'i4hh-tyaNto.mp4', 'INTEROCEPTIVE'),
(110, 'どぎまぎ', 'dogimagi', 'flurried, nervous', 'KK', 'i4kk-dogimagi.mp4', 'INTEROCEPTIVE'),
(111, 'のびのび', 'nobinobi', 'comfortable, peaceful', 'HH', 'i5hh-nobinobi.mp4', 'INTEROCEPTIVE'),
(112, 'はらはら', 'harahara', 'anxious, nervous', 'KK', 'i5kk-harahara.mp4', 'INTEROCEPTIVE'),
(113, 'のんびり', 'noNbiri', 'at leisure, in a relaxed manner', 'HH', 'i6hh-noNbiri.mp4', 'INTEROCEPTIVE'),
(114, 'ぎりぎり', 'girigiri', 'just barely, at the last moment', 'KK', 'i6kk-girigiri.mp4', 'INTEROCEPTIVE'),
(115, 'ほっこり', 'hokkori', 'feeling warm and fluffy, soft', 'HH', 'i7hh-hokkori.mp4', 'INTEROCEPTIVE'),
(116, 'ぞくぞく', 'zokuzoku', 'shivering, feeling chilly', 'KK', 'i7kk-zokuzoku.mp4', 'INTEROCEPTIVE'),
(117, 'ほっ', 'hoQ', 'with a feeling of relief', 'HH', 'i8hh-hoQ.mp4', 'INTEROCEPTIVE'),
(118, 'どきり', 'dokiri', 'being startled, getting a shock', 'KK', 'i8kk-dokiri.mp4', 'INTEROCEPTIVE'),
(119, 'ゆったり', 'yuttari', 'comfortable, calm, relaxed', 'HH', 'i9hh-yuttari.mp4', 'INTEROCEPTIVE'),
(120, 'どきどき', 'dokidoki', 'with a rapid heartbeat', 'KK', 'i9kk-dokidoki.mp4', 'INTEROCEPTIVE'),
(121, 'ごそごそ', 'gosogoso', 'with a rustling sound', 'HK', 'a0hk-gosogoso.mp4', 'AUDITORY'),
(122, 'かたかた', 'katakata', 'clattering, rattling', 'KH', 'a0kh-katakata.mp4', 'AUDITORY'),
(123, 'しとしと', 'sitosito', 'drizzling', 'HK', 'a1hk-sitosito.mp4', 'AUDITORY'),
(124, 'ばちゃばちゃ', 'batyabatya', 'splashing', 'KH', 'a1kh-batyabatya.mp4', 'AUDITORY'),
(125, 'じゃあじゃあ', 'zyaazyaa', 'noisily gushing', 'HK', 'a2hk-zyaazyaa.mp4', 'AUDITORY'),
(126, 'ぽたぽた', 'potapota', 'dripping, trickling', 'KH', 'a2kh-potapota.mp4', 'AUDITORY'),
(127, 'じりじり', 'ziriziri', 'sizzling, oozing', 'HK', 'a3hk-ziriziri.mp4', 'AUDITORY'),
(128, 'しゃきしゃき', 'syakisyaki', 'crisp, crunchy', 'KH', 'a3kh-syakisyaki.mp4', 'AUDITORY'),
(129, 'ずるずる', 'zuruzuru', 'with a slurp', 'HK', 'a4hk-zuruzuru.mp4', 'AUDITORY'),
(130, 'ぽりぽり', 'poripori', 'munching, crunching', 'KH', 'a4kh-poripori.mp4', 'AUDITORY'),
(131, 'そろりそろり', 'sororisorori', 'slowly and quietly', 'HK', 'a5hk-sororisorori.mp4', 'AUDITORY'),
(132, 'どたばた', 'dotabata', 'noisily, with heavy feet', 'KH', 'a5kh-dotabata.mp4', 'AUDITORY'),
(133, 'どさり', 'dosari', 'with a thud', 'HK', 'a6hk-dosari.mp4', 'AUDITORY'),
(134, 'かちっ', 'katiQ', 'click, snap', 'KH', 'a6kh-katiQ.mp4', 'AUDITORY'),
(135, 'どしどし', 'dosidosi', 'tramping, stomping', 'HK', 'a7hk-dosidosi.mp4', 'AUDITORY'),
(136, 'ぎしぎし', 'gisigisi', 'with a creak, squeak', 'KH', 'a7kh-gisigisi.mp4', 'AUDITORY'),
(137, 'ぼそり', 'bosori', 'in a whisper, in a murmur', 'HK', 'a8hk-bosori.mp4', 'AUDITORY'),
(138, 'きゃあきゃあ', 'kyaakyaa', 'shrieking, squealing', 'KH', 'a8kh-kyaakyaa.mp4', 'AUDITORY'),
(139, 'もごもご', 'mogomogo', 'mumbling, chewing', 'HK', 'a9hk-mogomogo.mp4', 'AUDITORY'),
(140, 'さくっ', 'sakuQ', 'with a crunch', 'KH', 'a9kh-sakuQ.mp4', 'AUDITORY'),
(141, 'くっきり', 'kukkiri', 'clearly, distinctly, sharply', 'HK', 'v0hk-kukkiri.mp4', 'VISUAL'),
(142, 'ちらちら', 'tiratira', 'flickering, fluttering', 'KH', 'v0kh-tiratira.mp4', 'VISUAL'),
(143, 'くりくり', 'kurikuri', 'big and round', 'HK', 'v1hk-kurikuri.mp4', 'VISUAL'),
(144, 'ぎざぎざ', 'gizagiza', 'jagged, serrated', 'KH', 'v1kh-gizagiza.mp4', 'VISUAL'),
(145, 'どんより', 'doNyori', 'dark, gloomy', 'HK', 'v2hk-doNyori.mp4', 'VISUAL'),
(146, 'きらきら', 'kirakira', 'glittering, sparkling', 'KH', 'v2kh-kirakira.mp4', 'VISUAL'),
(147, 'ぴたり', 'pitari', 'tightly connected, no space in between', 'HK', 'v3hk-pitari.mp4', 'VISUAL'),
(148, 'ひらひら', 'hirahira', 'fluttering, dangling', 'KH', 'v3kh-hirahira.mp4', 'VISUAL'),
(149, 'びっしり', 'bissiri', 'closely lined up, densely', 'HK', 'v4hk-bissiri.mp4', 'VISUAL'),
(150, 'ばらばら', 'barabara', 'scattered, in pieces', 'KH', 'v4kh-barabara.mp4', 'VISUAL'),
(151, 'ぶすり', 'busuri', 'poutingly, displeasure', 'HK', 'v5hk-busuri.mp4', 'VISUAL'),
(152, 'にこにこ', 'nikoniko', 'smilingly, with a grin', 'KH', 'v5kh-nikoniko.mp4', 'VISUAL'),
(153, 'ふんわり', 'huNwari', 'gently, airily, fluffy', 'HK', 'v6hk-huNwari.mp4', 'VISUAL'),
(154, 'ごつごつ', 'gotugotu', 'rugged, scragged, angular', 'KH', 'v6kh-gotugotu.mp4', 'VISUAL'),
(155, 'ぼんやり', 'boNyari', 'dim, faint, indistinct', 'HK', 'v7hk-boNyari.mp4', 'VISUAL'),
(156, 'きりっ', 'kiriQ', 'crisp appearance, stiffly', 'KH', 'v7kh-kiriQ.mp4', 'VISUAL'),
(157, 'まるまる', 'marumaru', 'plump, rotund, chubby', 'HK', 'v8hk-marumaru.mp4', 'VISUAL'),
(158, 'がりがり', 'garigari', 'very skinny, emaciated', 'KH', 'v8kh-garigari.mp4', 'VISUAL'),
(159, 'むくむく', 'mukumuku', 'billowing, plump', 'HK', 'v9hk-mukumuku.mp4', 'VISUAL'),
(160, 'ぼさぼさ', 'bosabosa', 'ruffled, disheveled', 'KH', 'v9kh-bosabosa.mp4', 'VISUAL'),
(161, 'うんざり', 'uNzari', 'boredom, tedious, fed up with', 'HK', 'i0hk-uNzari.mp4', 'INTEROCEPTIVE'),
(162, 'わくわく', 'wakuwaku', 'excitement, nervous', 'KH', 'i0kh-wakuwaku.mp4', 'INTEROCEPTIVE'),
(163, 'げんなり', 'geNnari', 'weary, fed up, dejected', 'HK', 'i1hk-geNnari.mp4', 'INTEROCEPTIVE'),
(164, 'がつがつ', 'gatugatu', 'ravenously, greedily', 'KH', 'i1kh-gatugatu.mp4', 'INTEROCEPTIVE'),
(165, 'しょぼん', 'syoboN', 'downhearted, dejected', 'HK', 'i2hk-syoboN.mp4', 'INTEROCEPTIVE'),
(166, 'るんるん', 'ruNruN', 'happy, elated, euphoric', 'KH', 'i2kh-ruNruN.mp4', 'INTEROCEPTIVE'),
(167, 'すっきり', 'sukkiri', 'refreshingly, with a feeling fo relief', 'HK', 'i3hk-sukkiri.mp4', 'INTEROCEPTIVE'),
(168, 'いらいら', 'iraira', 'to get irritated, annoyed', 'KH', 'i3kh-iraira.mp4', 'INTEROCEPTIVE'),
(169, 'ちゃんと', 'tyaNto', 'attentive, proper attitude', 'HK', 'i4hk-tyaNto.mp4', 'INTEROCEPTIVE'),
(170, 'どぎまぎ', 'dogimagi', 'flurried, nervous', 'KH', 'i4kh-dogimagi.mp4', 'INTEROCEPTIVE'),
(171, 'のびのび', 'nobinobi', 'comfortable, peaceful', 'HK', 'i5hk-nobinobi.mp4', 'INTEROCEPTIVE'),
(172, 'はらはら', 'harahara', 'anxious, nervous', 'KH', 'i5kh-harahara.mp4', 'INTEROCEPTIVE'),
(173, 'のんびり', 'noNbiri', 'at leisure, in a relaxed manner', 'HK', 'i6hk-noNbiri.mp4', 'INTEROCEPTIVE'),
(174, 'ぎりぎり', 'girigiri', 'just barely, at the last moment', 'KH', 'i6kh-girigiri.mp4', 'INTEROCEPTIVE'),
(175, 'ほっこり', 'hokkori', 'feeling warm and fluffy, soft', 'HK', 'i7hk-hokkori.mp4', 'INTEROCEPTIVE'),
(176, 'ぞくぞく', 'zokuzoku', 'shivering, feeling chilly', 'KH', 'i7kh-zokuzoku.mp4', 'INTEROCEPTIVE'),
(177, 'ほっ', 'hoQ', 'with a feeling of relief', 'HK', 'i8hk-hoQ.mp4', 'INTEROCEPTIVE'),
(178, 'どきり', 'dokiri', 'being startled, getting a shock', 'KH', 'i8kh-dokiri.mp4', 'INTEROCEPTIVE'),
(179, 'ゆったり', 'yuttari', 'comfortable, calm, relaxed', 'HK', 'i9hk-yuttari.mp4', 'INTEROCEPTIVE'),
(180, 'どきどき', 'dokidoki', 'with a rapid heartbeat', 'KH', 'i9kh-dokidoki.mp4', 'INTEROCEPTIVE');

INSERT INTO arena_rounds (id, prompt, left_ideophone_id, right_ideophone_id, correct_ideophone_id, condition_name, difficulty_level)
VALUES
(1, 'with a rustling sound', 1, 2, 1, 'CONDITION_1_SOKUON', 1),
(2, 'splashing', 3, 4, 4, 'CONDITION_1_SOKUON', 1),
(3, 'noisily gushing', 5, 6, 5, 'CONDITION_1_SOKUON', 1),
(4, 'crisp, crunchy', 7, 8, 8, 'CONDITION_1_SOKUON', 1),
(5, 'with a slurp', 9, 10, 9, 'CONDITION_1_SOKUON', 1),
(6, 'noisily, with heavy feet', 11, 12, 12, 'CONDITION_1_SOKUON', 1),
(7, 'with a thud', 13, 14, 13, 'CONDITION_1_SOKUON', 1),
(8, 'with a creak, squeak', 15, 16, 16, 'CONDITION_1_SOKUON', 1),
(9, 'in a whisper, in a murmur', 17, 18, 17, 'CONDITION_1_SOKUON', 1),
(10, 'with a crunch', 19, 20, 20, 'CONDITION_1_SOKUON', 1),
(11, 'clearly, distinctly, sharply', 21, 22, 21, 'CONDITION_1_SOKUON', 1),
(12, 'jagged, serrated', 23, 24, 24, 'CONDITION_1_SOKUON', 1),
(13, 'dark, gloomy', 25, 26, 25, 'CONDITION_1_SOKUON', 1),
(14, 'fluttering, dangling', 27, 28, 28, 'CONDITION_1_SOKUON', 1),
(15, 'closely lined up, densely', 29, 30, 29, 'CONDITION_1_SOKUON', 1),
(16, 'smilingly, with a grin', 31, 32, 32, 'CONDITION_1_SOKUON', 1),
(17, 'gently, airily, fluffy', 33, 34, 33, 'CONDITION_1_SOKUON', 1),
(18, 'crisp appearance, stiffly', 35, 36, 36, 'CONDITION_1_SOKUON', 1),
(19, 'plump, rotund, chubby', 37, 38, 37, 'CONDITION_1_SOKUON', 1),
(20, 'ruffled, disheveled', 39, 40, 40, 'CONDITION_1_SOKUON', 1),
(21, 'boredom, tedious, fed up with', 41, 42, 41, 'CONDITION_1_SOKUON', 1),
(22, 'ravenously, greedily', 43, 44, 44, 'CONDITION_1_SOKUON', 1),
(23, 'downhearted, dejected', 45, 46, 45, 'CONDITION_1_SOKUON', 1),
(24, 'to get irritated, annoyed', 47, 48, 48, 'CONDITION_1_SOKUON', 1),
(25, 'attentive, proper attitude', 49, 50, 49, 'CONDITION_1_SOKUON', 1),
(26, 'anxious, nervous', 51, 52, 52, 'CONDITION_1_SOKUON', 1),
(27, 'at leisure, in a relaxed manner', 53, 54, 53, 'CONDITION_1_SOKUON', 1),
(28, 'shivering, feeling chilly', 55, 56, 56, 'CONDITION_1_SOKUON', 1),
(29, 'with a feeling of relief', 57, 58, 57, 'CONDITION_1_SOKUON', 1),
(30, 'with a rapid heartbeat', 59, 60, 60, 'CONDITION_1_SOKUON', 1),
(31, 'with a rustling sound', 61, 62, 61, 'CONDITION_2_SOKUON', 1),
(32, 'splashing', 63, 64, 64, 'CONDITION_2_SOKUON', 1),
(33, 'noisily gushing', 65, 66, 65, 'CONDITION_2_SOKUON', 1),
(34, 'crisp, crunchy', 67, 68, 68, 'CONDITION_2_SOKUON', 1),
(35, 'with a slurp', 69, 70, 69, 'CONDITION_2_SOKUON', 1),
(36, 'noisily, with heavy feet', 71, 72, 72, 'CONDITION_2_SOKUON', 1),
(37, 'with a thud', 73, 74, 73, 'CONDITION_2_SOKUON', 1),
(38, 'with a creak, squeak', 75, 76, 76, 'CONDITION_2_SOKUON', 1),
(39, 'in a whisper, in a murmur', 77, 78, 77, 'CONDITION_2_SOKUON', 1),
(40, 'with a crunch', 79, 80, 80, 'CONDITION_2_SOKUON', 1),
(41, 'clearly, distinctly, sharply', 81, 82, 81, 'CONDITION_2_SOKUON', 1),
(42, 'jagged, serrated', 83, 84, 84, 'CONDITION_2_SOKUON', 1),
(43, 'dark, gloomy', 85, 86, 85, 'CONDITION_2_SOKUON', 1),
(44, 'fluttering, dangling', 87, 88, 88, 'CONDITION_2_SOKUON', 1),
(45, 'closely lined up, densely', 89, 90, 89, 'CONDITION_2_SOKUON', 1),
(46, 'smilingly, with a grin', 91, 92, 92, 'CONDITION_2_SOKUON', 1),
(47, 'gently, airily, fluffy', 93, 94, 93, 'CONDITION_2_SOKUON', 1),
(48, 'crisp appearance, stiffly', 95, 96, 96, 'CONDITION_2_SOKUON', 1),
(49, 'plump, rotund, chubby', 97, 98, 97, 'CONDITION_2_SOKUON', 1),
(50, 'ruffled, disheveled', 99, 100, 100, 'CONDITION_2_SOKUON', 1),
(51, 'boredom, tedious, fed up with', 101, 102, 101, 'CONDITION_2_SOKUON', 1),
(52, 'ravenously, greedily', 103, 104, 104, 'CONDITION_2_SOKUON', 1),
(53, 'downhearted, dejected', 105, 106, 105, 'CONDITION_2_SOKUON', 1),
(54, 'to get irritated, annoyed', 107, 108, 108, 'CONDITION_2_SOKUON', 1),
(55, 'attentive, proper attitude', 109, 110, 109, 'CONDITION_2_SOKUON', 1),
(56, 'anxious, nervous', 111, 112, 112, 'CONDITION_2_SOKUON', 1),
(57, 'at leisure, in a relaxed manner', 113, 114, 113, 'CONDITION_2_SOKUON', 1),
(58, 'shivering, feeling chilly', 115, 116, 116, 'CONDITION_2_SOKUON', 1),
(59, 'with a feeling of relief', 117, 118, 117, 'CONDITION_2_SOKUON', 1),
(60, 'with a rapid heartbeat', 119, 120, 120, 'CONDITION_2_SOKUON', 1),
(61, 'with a rustling sound', 121, 122, 121, 'CONDITION_3_SOKUON', 1),
(62, 'splashing', 123, 124, 124, 'CONDITION_3_SOKUON', 1),
(63, 'noisily gushing', 125, 126, 125, 'CONDITION_3_SOKUON', 1),
(64, 'crisp, crunchy', 127, 128, 128, 'CONDITION_3_SOKUON', 1),
(65, 'with a slurp', 129, 130, 129, 'CONDITION_3_SOKUON', 1),
(66, 'noisily, with heavy feet', 131, 132, 132, 'CONDITION_3_SOKUON', 1),
(67, 'with a thud', 133, 134, 133, 'CONDITION_3_SOKUON', 1),
(68, 'with a creak, squeak', 135, 136, 136, 'CONDITION_3_SOKUON', 1),
(69, 'in a whisper, in a murmur', 137, 138, 137, 'CONDITION_3_SOKUON', 1),
(70, 'with a crunch', 139, 140, 140, 'CONDITION_3_SOKUON', 1),
(71, 'clearly, distinctly, sharply', 141, 142, 141, 'CONDITION_3_SOKUON', 1),
(72, 'jagged, serrated', 143, 144, 144, 'CONDITION_3_SOKUON', 1),
(73, 'dark, gloomy', 145, 146, 145, 'CONDITION_3_SOKUON', 1),
(74, 'fluttering, dangling', 147, 148, 148, 'CONDITION_3_SOKUON', 1),
(75, 'closely lined up, densely', 149, 150, 149, 'CONDITION_3_SOKUON', 1),
(76, 'smilingly, with a grin', 151, 152, 152, 'CONDITION_3_SOKUON', 1),
(77, 'gently, airily, fluffy', 153, 154, 153, 'CONDITION_3_SOKUON', 1),
(78, 'crisp appearance, stiffly', 155, 156, 156, 'CONDITION_3_SOKUON', 1),
(79, 'plump, rotund, chubby', 157, 158, 157, 'CONDITION_3_SOKUON', 1),
(80, 'ruffled, disheveled', 159, 160, 160, 'CONDITION_3_SOKUON', 1),
(81, 'boredom, tedious, fed up with', 161, 162, 161, 'CONDITION_3_SOKUON', 1),
(82, 'ravenously, greedily', 163, 164, 164, 'CONDITION_3_SOKUON', 1),
(83, 'downhearted, dejected', 165, 166, 165, 'CONDITION_3_SOKUON', 1),
(84, 'to get irritated, annoyed', 167, 168, 168, 'CONDITION_3_SOKUON', 1),
(85, 'attentive, proper attitude', 169, 170, 169, 'CONDITION_3_SOKUON', 1),
(86, 'anxious, nervous', 171, 172, 172, 'CONDITION_3_SOKUON', 1),
(87, 'at leisure, in a relaxed manner', 173, 174, 173, 'CONDITION_3_SOKUON', 1),
(88, 'shivering, feeling chilly', 175, 176, 176, 'CONDITION_3_SOKUON', 1),
(89, 'with a feeling of relief', 177, 178, 177, 'CONDITION_3_SOKUON', 1),
(90, 'with a rapid heartbeat', 179, 180, 180, 'CONDITION_3_SOKUON', 1);
