spring.application.name=ideophone-arena-api
spring.profiles.active=local
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
server.port=8081
